language: python
arch:
  - amd64
  - ppc64le

matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"
    - python: "3.7-dev"
    - python: "3.6-dev"
    - arch: ppc64le
      python: "nightly"
  exclude:
    - arch: ppc64le
      python:
        - "3.4"
        - "3.5"

python:
  - "nightly" # currently points to 3.7-dev
  - "3.7-dev"
  - "3.6-dev"
  - "3.6"
  - "3.5"
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - |
        if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
          sudo chown -R $USER:$GROUP ~/.cache/pip/wheels;
        fi
    - "pip install -e ."
script:
    - "python ./setup.py test"
