language: python
arch:
  - amd64
  - ppc64le

python:
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - |
        if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
          sudo chown -R $USER:$GROUP ~/.cache/pip/wheels;
        fi
    - "pip install -e poetry"
    - "poetry install"
script:
    - "poetry run pytest -sxv"
